-- =====================================================
-- BASE DE DATOS TIENDA DE MOTOS
-- ORACLE DATABASE 19c
-- =====================================================

-- =====================================================
-- ELIMINAR TABLAS SI EXISTEN
-- =====================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DETALLE_VENTA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VENTAS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MOTOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- =====================================================
-- ELIMINAR SEQUENCES
-- =====================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTES';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOTOS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VENTAS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DETALLE_VENTA';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- =====================================================
-- TABLA CLIENTES
-- =====================================================

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    DOCUMENTO VARCHAR2(20) UNIQUE NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100)
);

-- =====================================================
-- TABLA MOTOS
-- =====================================================

CREATE TABLE MOTOS (
    ID_MOTO NUMBER PRIMARY KEY,
    MARCA VARCHAR2(50) NOT NULL,
    MODELO VARCHAR2(50) NOT NULL,
    CILINDRADA NUMBER(5) NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    PRECIO NUMBER(12,2) NOT NULL,
    STOCK NUMBER DEFAULT 0 NOT NULL
);

-- =====================================================
-- TABLA VENTAS
-- =====================================================

CREATE TABLE VENTAS (
    ID_VENTA NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    FECHA_VENTA DATE DEFAULT SYSDATE NOT NULL,
    TOTAL NUMBER(12,2) DEFAULT 0 NOT NULL,

    CONSTRAINT FK_VENTA_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
);

-- =====================================================
-- TABLA DETALLE_VENTA
-- =====================================================

CREATE TABLE DETALLE_VENTA (
    ID_DETALLE NUMBER PRIMARY KEY,
    ID_VENTA NUMBER NOT NULL,
    ID_MOTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO NUMBER(12,2) NOT NULL,
    SUBTOTAL NUMBER(12,2) NOT NULL,

    CONSTRAINT FK_DETALLE_VENTA
        FOREIGN KEY (ID_VENTA)
        REFERENCES VENTAS(ID_VENTA),

    CONSTRAINT FK_DETALLE_MOTO
        FOREIGN KEY (ID_MOTO)
        REFERENCES MOTOS(ID_MOTO)
);

-- =====================================================
-- SEQUENCES
-- =====================================================

CREATE SEQUENCE SEQ_CLIENTES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_MOTOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_VENTAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_DETALLE_VENTA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- =====================================================
-- DATOS DE PRUEBA - CLIENTES
-- =====================================================

INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE, APELLIDO, DOCUMENTO, TELEFONO, CORREO)
VALUES
(SEQ_CLIENTES.NEXTVAL, 'Carlos', 'Rodriguez',
 '1001001001', '3001112233', 'carlos@gmail.com');

INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE, APELLIDO, DOCUMENTO, TELEFONO, CORREO)
VALUES
(SEQ_CLIENTES.NEXTVAL, 'Andres', 'Martinez',
 '1001001002', '3002223344', 'andres@gmail.com');

INSERT INTO CLIENTES
(ID_CLIENTE, NOMBRE, APELLIDO, DOCUMENTO, TELEFONO, CORREO)
VALUES
(SEQ_CLIENTES.NEXTVAL, 'Laura', 'Gomez',
 '1001001003', '3003334455', 'laura@gmail.com');

-- =====================================================
-- DATOS DE PRUEBA - MOTOS
-- =====================================================

INSERT INTO MOTOS
(ID_MOTO, MARCA, MODELO, CILINDRADA, ANIO, PRECIO, STOCK)
VALUES
(SEQ_MOTOS.NEXTVAL, 'Yamaha', 'MT-03', 321, 2025, 28000000, 5);

INSERT INTO MOTOS
(ID_MOTO, MARCA, MODELO, CILINDRADA, ANIO, PRECIO, STOCK)
VALUES
(SEQ_MOTOS.NEXTVAL, 'Honda', 'CB190R', 184, 2025, 18500000, 8);

INSERT INTO MOTOS
(ID_MOTO, MARCA, MODELO, CILINDRADA, ANIO, PRECIO, STOCK)
VALUES
(SEQ_MOTOS.NEXTVAL, 'Suzuki', 'GSX-S150', 147, 2024, 16500000, 6);

INSERT INTO MOTOS
(ID_MOTO, MARCA, MODELO, CILINDRADA, ANIO, PRECIO, STOCK)
VALUES
(SEQ_MOTOS.NEXTVAL, 'Kawasaki', 'Ninja 400', 399, 2025, 35000000, 3);

INSERT INTO MOTOS
(ID_MOTO, MARCA, MODELO, CILINDRADA, ANIO, PRECIO, STOCK)
VALUES
(SEQ_MOTOS.NEXTVAL, 'BMW', 'G 310 R', 313, 2025, 32000000, 4);

COMMIT;

-- =====================================================
-- CONSULTAS DE PRUEBA
-- =====================================================

SELECT * FROM CLIENTES;

SELECT * FROM MOTOS;

SELECT * FROM VENTAS;

SELECT * FROM DETALLE_VENTA;